# Generated by Django 6.0.3 on 2026-05-26 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('destination_type', models.CharField(choices=[('WEB', 'Website'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('MAP', 'Map'), ('TEXT', 'Text')], max_length=10)),
                ('destination_value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='core.qrcode')),
            ],
            options={
                'db_table': 'qr_scan_events',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('original_url', models.URLField(max_length=2000)),
                ('total_clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'short_urls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortUrlClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='core.shorturl')),
            ],
            options={
                'db_table': 'short_url_click_events',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['slug'], name='qr_codes_slug_50789b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', 'created_at'], name='qr_codes_user_id_4452da_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='qr_scan_eve_qr_code_e11f50_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanevent',
            index=models.Index(fields=['country', 'city'], name='qr_scan_eve_country_c70432_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['slug'], name='short_urls_slug_87d374_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['user', 'created_at'], name='short_urls_user_id_b44c23_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturlclickevent',
            index=models.Index(fields=['short_url', 'clicked_at'], name='short_url_c_short_u_22ced9_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturlclickevent',
            index=models.Index(fields=['country', 'city'], name='short_url_c_country_340863_idx'),
        ),
    ]
