# Generated by Django 6.0.3 on 2026-09-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='customization',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
