# Generated by Django 6.0.3 on 2026-09-29 22:51

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qrcode_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanevent',
            name='ip_address',
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='qrscanevent',
            name='user_agent',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shorturlclickevent',
            name='ip_address',
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='shorturlclickevent',
            name='user_agent',
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
